title: Pronoy Chopra
author: Pronoy Chopra
email: contact@pronoy.in
description: > # this means to ignore newlines until "show_exerpts:"
  All things Python and hardware and most recently gamedev with Unity
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Pronoy Chopra
  tagline: Developer/Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  analytics_id: UA-31320505-1

  # generate social links in footer
  social_links:
    twitter: pronoyc
    github:  darksector
    linkedIn: in/pronoychopra
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed